[package]
name = "alter_ids_for_sql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.21", features = ["cargo", "derive"] }
uuid = "1.4.1"
